version: "3.9"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Admin123$
      MYSQL_DATABASE: curd
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin123$
  api:
#    build:
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql